--List all customers along with their invoices (include customers with no invoices).
select * from customer c join invoice i on c.CustomerId=i.CustomerId;

--Q2.Show customer name and total number of invoices for each customer.
select c.FirstName,c.LastName,count(i.InvoiceId) as total_invoices from customer c 
left join invoice i on c.CustomerId=i.customerid
group by c.firstname,c.lastname,c.CustomerId;

--Q3.list all tracks with their album name and artist name
select t.name as track_name,al.title as album_name,ar.name as artist_name from track t 
join album al on t.albumid=al.AlbumId join artist ar on al.ArtistId=ar.ArtistId;

--Q4.Display all invoices along with customer country
select i.*,c.Country as country from invoice i join Customer c on i.CustomerId=c.CustomerId;

--Q5.Show all tracks and their genre names.
select t.name,g.name from track t join genre g on t.GenreId=g.GenreId;

--Q6.List customers who have made at least one purchase.
select distinct c.FirstName,c.LastName from Customer c join invoice i on c.CustomerId=i.CustomerId;

select c.firstname,c.lastname from customer c  
where exists(select 1 from invoice i where i.CustomerId=c.CustomerId);

--Q7.Find all albums that have at least one track.
select al.title from album al 
where exists(select 1 from track t where t.AlbumId=al.AlbumId);

--Q8.Display each invoice and the total number of tracks in it.
select i.InvoiceId,count(t.TrackId) as total from Invoice i 
join InvoiceLine il on i.InvoiceId=il.InvoiceId join track t on il.TrackId=t.TrackId
group by i.InvoiceId;

--Q9.Show all artists and their albums (include artists with no albums)
select ar.name,al.title from artist ar left join album al on ar.ArtistId=al.ArtistId;

--Q10 List employees along with their managers’ names
-- List employees along with their managers’ names

SELECT
    e.FirstName  AS employee_first_name,
    e.LastName   AS employee_last_name,
    m.FirstName  AS manager_first_name,
    m.LastName   AS manager_last_name
FROM Employee e
LEFT JOIN Employee m
    ON e.ReportsTo = m.EmployeeId;

--Q11.Find total amount spent by each customer.
select c.CustomerId,c.FirstName,c.LastName,sum(i.Total) as total_amt 
from Customer c join Invoice i on c.CustomerId=i.CustomerId GROUP BY
c.CustomerId,c.FirstName,c.LastName order by total_amt desc;

--Q12.Find customers who spent more than the average customer spending.
select c.CustomerId,c.FirstName,c.LastName,sum(i.Total) as total_amt from customer c
join invoice i
 on c.CustomerId=i.CustomerId group by c.CustomerId,c.firstname,c.LastName
having sum(i.total)>(select avg(customer_total) from (select sum(total) as customer_total from invoice group by CustomerId) t )
order by total_amt desc;

--Q13.Show top 5 customers by total spending.
select c.CustomerId,c.firstname,c.lastname,sum(i.total) as total_amnt
from customer c join invoice i on c.customerid=i.customerid GROUP BY
c.customerid,c.firstname,c.lastname order by total_amnt desc limit 5;

--Q14.Find total revenue generated by each artist.
select ar.name,sum(il.UnitPrice*il.Quantity) as total_amt from Artist ar join Album al 
on ar.ArtistId=al.ArtistId join track t on al.albumid=t.albumid join InvoiceLine il 
on t.trackid=il.trackid  group by ar.ArtistId,ar.Name
order by total_amt desc;

--Q15.Find artists whose total revenue is above average artist revenue

SELECT
    ar.Name,
    SUM(il.UnitPrice * il.Quantity) AS total_amt
FROM Artist ar
JOIN Album al
    ON ar.ArtistId = al.ArtistId
JOIN Track t
    ON al.AlbumId = t.AlbumId
JOIN InvoiceLine il
    ON t.TrackId = il.TrackId
GROUP BY
    ar.ArtistId,
    ar.Name
HAVING SUM(il.UnitPrice * il.Quantity) >
(
    SELECT AVG(artist_revenue)
    FROM
    (
        SELECT
            SUM(il.UnitPrice * il.Quantity) AS artist_revenue
        FROM Artist ar
        JOIN Album al
            ON ar.ArtistId = al.ArtistId
        JOIN Track t
            ON al.AlbumId = t.AlbumId
        JOIN InvoiceLine il
            ON t.TrackId = il.TrackId
        GROUP BY
            ar.ArtistId
    ) sub
)
ORDER BY total_amt DESC;

--Q16.Display total number of tracks sold for each genre.
select g.name,sum(il.Quantity) as total_sold from genre g join track t on g.GenreId=t.genreid join InvoiceLine il on t.trackid=il.trackid
group by g.GenreId,g.name order by total_sold desc;

--Q17.Find the most popular genre (by quantity sold).
select g.name,sum(il.Quantity) as total_sold from genre g join track t on g.GenreId=t.genreid join InvoiceLine il on t.trackid=il.trackid
group by g.GenreId,g.name order by total_sold desc limit 1;

SELECT
    g.Name,
    SUM(il.Quantity) AS total_sold
FROM Genre g
JOIN Track t ON g.GenreId = t.GenreId
JOIN InvoiceLine il ON t.TrackId = il.TrackId
GROUP BY g.GenreId, g.Name
HAVING SUM(il.Quantity) =
(
    SELECT MAX(genre_sales)
    FROM (
        SELECT SUM(il.Quantity) AS genre_sales
        FROM Genre g
        JOIN Track t ON g.GenreId = t.GenreId
        JOIN InvoiceLine il ON t.TrackId = il.TrackId
        GROUP BY g.GenreId
    ) sub
);

--Q18.Find customers who purchased tracks from more than 3 different genres.
select c.FirstName,c.LastName,g.name,count(distinct(g.GenreId)) as genre_count from customer C
join Invoice i on c.CustomerId=i.customerid join 
InvoiceLine il on i.InvoiceId=il.InvoiceId
join track t on il.trackid=t.trackid join genre G
on t.genreid=g.genreid  group by c.CustomerId,c.FirstName,c.LastName
having count(DISTINCT g.genreid)>3 order by genre_count desc;

--Q19.Find albums that have more tracks than the average tracks per album
select 
al.AlbumId,al.Title,count(TrackId) as count
from Album al join track t on al.AlbumId=t.AlbumId
group by 
al.title,al.AlbumId having count(TrackId)>
(select avg(total_count) 
from (select count(TrackId) as total_count 
from track group by albumid) sub) order by count desc;

select BillingCountry,sum(total)as total_sell from invoice group by BillingCountry;
select BillingCountry,avg(total)as total_sell from invoice group by BillingCountry;
--Q20.Find countries where total sales are above average country sales.
select i.BillingCountry,sum(i.total) 
as total from Invoice i group by i.BillingCountry 
having sum(total)>(select avg(total_sell) from (select sum(total)as total_sell from invoice group by BillingCountry) sub)
order by total desc;

select i.BillingCountry,sum(il.Quantity*il.UnitPrice) as total from invoice i join 
InvoiceLine il on i.InvoiceId=il.InvoiceId
group by i.BillingCountry
having sum(il.Quantity*il.UnitPrice)>(select avg(total_sell) from (select sum(il.quantity*il.UnitPrice)as total_sell from InvoiceLine il join invoice i on il.InvoiceId=i.InvoiceId 
group by i.BillingCountry) sub) order by total desc;

-- Q21: Find tracks that have never been sold

SELECT
    t.TrackId,
    t.Name
FROM Track t
WHERE NOT EXISTS
(
    SELECT 1
    FROM InvoiceLine il
    WHERE il.TrackId = t.TrackId
);

--Q22.Find customers who have purchased all their tracks from only one genre.
select c.CustomerId,c.FirstName,c.lastname,count(distinct g.genreid) as total,g.Name from customer c
 join invoice i on c.CustomerId=i.CustomerId
  join InvoiceLine il on i.InvoiceId=il.InvoiceId
 join track t on il.TrackId=t.TrackId 
 join genre g
on t.genreid=g.GenreId group by c.CustomerId,
c.FirstName,c.LastName having count(distinct g.genreid)=1;

--Q23.Find the invoice that has the highest total value.
select * from invoice
 where total=(select max(total) from invoice);

 --Q24.Find the employee who supported the maximum number of customers.
 SELECT
    e.EmployeeId,
    e.FirstName,
    e.LastName,
    COUNT(c.CustomerId) AS customer_count
FROM Employee e
JOIN Customer c
    ON e.EmployeeId = c.SupportRepId
GROUP BY
    e.EmployeeId,
    e.FirstName,
    e.LastName
ORDER BY
    customer_count DESC
LIMIT 1;

--25.Find customers who have not purchased anything in the last invoice date.
-- Q25: Find customers who have not purchased anything on the latest invoice date

SELECT
    c.CustomerId,
    c.FirstName,
    c.LastName
FROM Customer c
WHERE NOT EXISTS
(
    SELECT 1
    FROM Invoice i
    WHERE i.CustomerId = c.CustomerId
      AND i.InvoiceDate =
      (
          SELECT MAX(InvoiceDate)
          FROM Invoice
      )
);

--Q26.Find customers who spent more than the overall average invoice amount.
select 
    c.CustomerId,c.FirstName,c.LastName,sum(i.total) as total_amt 
    from customer c
join 
    invoice i on c.CustomerId=i.CustomerId 
group by 
      c.CustomerId,c.FirstName,c.LastName
having sum(i.total)>
(select 
avg(total) as total_avg
 from 
 invoice)
order by 
total_amt desc;

--Q27.Find invoices whose total is greater than the average invoice total.
select 
    i.InvoiceId,
    sum(i.total) as total_amt 
from 
    invoice i
group by 
    i.InvoiceId
having 
sum(i.total)>
(select 
    avg(total_invoice)
from 
(select 
    sum(total)as total_invoice 
from 
    invoice group by InvoiceId))
order by 
    total_amt desc;


-- Q27: Find invoices whose total is greater than the average invoice total

SELECT
    InvoiceId,
    Total
FROM Invoice
WHERE Total >
(
    SELECT AVG(Total)
    FROM Invoice
)
ORDER BY Total DESC;

--Q28.Find albums that contain at least one track longer than the average track length.
select 
   al.AlbumId,
   al.title
from 
   album al
WHERE EXISTS
(
    select 1
    from track t
    where al.AlbumId=t.AlbumId 
    and t.Bytes>(select avg(Bytes) from track)
);
--alternate solution
SELECT 
    al.AlbumId,
    al.Title
FROM Album al
JOIN Track t ON t.AlbumId = al.AlbumId
GROUP BY al.AlbumId, al.Title
HAVING MAX(t.Bytes) > (SELECT AVG(Bytes) FROM Track);

--Q29.Find customers who have never purchased Rock genre tracks.
SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName
FROM Customer c
WHERE NOT EXISTS (
    SELECT 1
    FROM Invoice i
    JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId
    JOIN Track t ON il.TrackId = t.TrackId
    JOIN Genre g ON t.GenreId = g.GenreId
    WHERE i.CustomerId = c.CustomerId
      AND g.Name = 'Rock'
);
--Q.30.Find artists who have never sold a track.
SELECT
    ar.ArtistId,
    ar.name
FROM
    artist ar
where not EXISTS(
    select 1
    from 
    album Al
    join track T on al.AlbumId=t.AlbumId
    join invoiceline il
    on t.trackid=il.trackid
    where al.ArtistId=ar.ArtistId
);

--Q31.Find genres that generated less revenue than the average genre revenue.
select 
    g.genreid,
    g.Name,
    sum(il.quantity*il.UnitPrice) as total_amt
from 
    genre g
JOIN track ton g.genreid=t.GenreId
JOIN invoiceline ilon t.trackid=il.TrackId
group by 
    g.genreid,
    g.name
having sum(il.quantity*il.UnitPrice)<
(select 
    avg(total_price)
FROM
(select 
    sum(il.quantity*il.UnitPrice) as total_price 
from 
    invoiceline il 
join track t on il.trackid=t.TrackId
join genre g on t.genreid=g.genreid 
group by 
g.genreid) sub)
order by total_amt desc;

-- Q32. Find customers who purchased the most expensive track
SELECT DISTINCT
    c.CustomerId,
    c.FirstName,
    c.LastName
FROM Customer c
JOIN Invoice i 
    ON c.CustomerId = i.CustomerId
JOIN InvoiceLine il 
    ON i.InvoiceId = il.InvoiceId
JOIN Track t 
    ON il.TrackId = t.TrackId
WHERE t.UnitPrice = (
    SELECT MAX(UnitPrice) 
    FROM Track
);

--Q33.Find customers who share the same support representative and have similar spending patterns (above average)
/* i have to find the customer having same support and similat spending patter so i need to group by the customers on the two basis
first on the basis of support and then who are above average so i can make cases to mark above average and the group it*/
-- Q33. Find customers who share the same support representative
-- and have above-average spending patterns

SELECT
    c.SupportRepId,
    c.CustomerId,
    c.FirstName,
    c.LastName,
    SUM(il.Quantity * il.UnitPrice) AS total_spent
FROM Customer c
JOIN Invoice i 
    ON c.CustomerId = i.CustomerId
JOIN InvoiceLine il 
    ON i.InvoiceId = il.InvoiceId
GROUP BY
    c.SupportRepId,
    c.CustomerId,
    c.FirstName,
    c.LastName
HAVING
    SUM(il.Quantity * il.UnitPrice) >
    (
        SELECT AVG(customer_total)
        FROM (
            SELECT
                SUM(il.Quantity * il.UnitPrice) AS customer_total
            FROM Customer c
            JOIN Invoice i ON c.CustomerId = i.CustomerId
            JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId
            GROUP BY c.CustomerId
        ) sub
    )
ORDER BY
    c.SupportRepId,
    total_spent DESC;

SELECT
    c.CustomerId,
    SUM(il.Quantity * il.UnitPrice) AS total_spent,
    CASE
        WHEN SUM(il.Quantity * il.UnitPrice) >
             (
               SELECT AVG(total_amt)
               FROM (
                   SELECT SUM(il.Quantity * il.UnitPrice) AS total_amt
                   FROM InvoiceLine
                   GROUP BY InvoiceId
               ) sub
        THEN 'Above Average'
        ELSE 'Below Average'
    END AS spending_category
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId
GROUP BY c.CustomerId;


SELECT
    COUNT(
        CASE
            WHEN Genre = 'Rock' THEN 1
        END
    ) AS rock_count,
    COUNT(
        CASE
            WHEN Genre = 'Jazz' THEN 1
        END
    ) AS jazz_count
FROM Track;
